# Generated by Django 4.2.18 on 2025-01-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_post_title_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
